apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-deployment
spec:
  selector:
    matchLabels:
      app: ocr
  replicas: 1 
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
        - name: ocr
          image:  zigzigcheers/ocr:v2
          ports:
          - containerPort: 8081
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 64Mi
              cpu: '0.5'

---
apiVersion: v1
kind: Service
metadata:
  name:  ocr-service
spec:
  selector:
    app: ocr
  type: LoadBalancer
  ports:
  - targetPort: 8081
    port: 8081
    nodePort: 30081
    protocol: TCP