apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1 
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image:  registry
          ports:
          - containerPort: 5000
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 64Mi
              cpu: '0.5'

---
apiVersion: v1
kind: Service
metadata:
  name:  registry-service
spec:
  selector:
    app: registry
  type: LoadBalancer
  ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30000
    protocol: TCP