apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-deployment
spec:
  selector:
    matchLabels:
      app: translator
  replicas: 1 
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
        - name: translator
          image:  zigzigcheers/private_translator:v2
          ports:
          - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: translator-service
spec:
  selector:
    app: translator
  ports:
  - targetPort: 8082
    port: 8082
    protocol: TCP