apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-deployment
spec:
  selector:
    matchLabels:
      app: tts
  replicas: 1 
  template:
    metadata:
      labels:
        app: tts
    spec:
      containers:
        - name: tts
          image:  zigzigcheers/private_tts:v2
          ports:
          - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: tts-service
spec:
  selector:
    app: tts
  ports:
  - targetPort: 8083
    port: 8083
    protocol: TCP